from alembic import op
import sqlalchemy as sa
revision="0001_initial";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 op.create_table("users",sa.Column("id",sa.Integer,primary_key=True),sa.Column("email",sa.String(255),unique=True,nullable=False),sa.Column("display_name",sa.String(80),nullable=False),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("role",sa.String(20),server_default="READER",nullable=False),sa.Column("is_active",sa.Boolean,server_default=sa.true(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_table("categories",sa.Column("id",sa.Integer,primary_key=True),sa.Column("name",sa.String(80),unique=True,nullable=False),sa.Column("slug",sa.String(100),unique=True,nullable=False))
 op.create_table("tags",sa.Column("id",sa.Integer,primary_key=True),sa.Column("name",sa.String(50),unique=True,nullable=False),sa.Column("slug",sa.String(70),unique=True,nullable=False))
 op.create_table("writings",sa.Column("id",sa.Integer,primary_key=True),sa.Column("title",sa.String(220),nullable=False),sa.Column("slug",sa.String(240),unique=True,nullable=False),sa.Column("excerpt",sa.Text),sa.Column("content",sa.Text,nullable=False),sa.Column("cover_image_url",sa.String(1000)),sa.Column("status",sa.String(20),server_default="DRAFT",nullable=False),sa.Column("featured",sa.Boolean,server_default=sa.false(),nullable=False),sa.Column("view_count",sa.Integer,server_default="0",nullable=False),sa.Column("category_id",sa.Integer,sa.ForeignKey("categories.id",ondelete="SET NULL")),sa.Column("author_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True)))
 op.create_table("writing_tags",sa.Column("writing_id",sa.Integer,sa.ForeignKey("writings.id",ondelete="CASCADE"),primary_key=True),sa.Column("tag_id",sa.Integer,sa.ForeignKey("tags.id",ondelete="CASCADE"),primary_key=True))
 op.create_table("comments",sa.Column("id",sa.Integer,primary_key=True),sa.Column("content",sa.Text,nullable=False),sa.Column("status",sa.String(20),server_default="VISIBLE",nullable=False),sa.Column("author_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("writing_id",sa.Integer,sa.ForeignKey("writings.id",ondelete="CASCADE"),nullable=False),sa.Column("parent_id",sa.Integer,sa.ForeignKey("comments.id",ondelete="CASCADE")),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_table("writing_likes",sa.Column("id",sa.Integer,primary_key=True),sa.Column("writing_id",sa.Integer,sa.ForeignKey("writings.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE")),sa.Column("visitor_key",sa.String(128)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint("(user_id IS NOT NULL) OR (visitor_key IS NOT NULL)"),sa.UniqueConstraint("writing_id","user_id"),sa.UniqueConstraint("writing_id","visitor_key"))
 op.create_table("comment_likes",sa.Column("id",sa.Integer,primary_key=True),sa.Column("comment_id",sa.Integer,sa.ForeignKey("comments.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.UniqueConstraint("comment_id","user_id"))
 op.create_table("bookmarks",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("writing_id",sa.Integer,sa.ForeignKey("writings.id",ondelete="CASCADE"),nullable=False),sa.UniqueConstraint("user_id","writing_id"))
 op.create_table("notifications",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("actor_id",sa.Integer,sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("type",sa.String(40),nullable=False),sa.Column("message",sa.String(500),nullable=False),sa.Column("comment_id",sa.Integer,sa.ForeignKey("comments.id",ondelete="SET NULL")),sa.Column("writing_id",sa.Integer,sa.ForeignKey("writings.id",ondelete="SET NULL")),sa.Column("is_read",sa.Boolean,server_default=sa.false(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_table("reports",sa.Column("id",sa.Integer,primary_key=True),sa.Column("comment_id",sa.Integer,sa.ForeignKey("comments.id",ondelete="CASCADE"),nullable=False),sa.Column("reporter_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("reason",sa.String(500),nullable=False),sa.Column("status",sa.String(20),server_default="OPEN",nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
def downgrade():
 for t in ["reports","notifications","comment_likes","writing_likes","comments","writing_tags","writings","tags","categories","users"]: op.drop_table(t)
